/* Session observer actions */
export const SESSION_CHANGED = 'SESSION_CHANGED';

/* Session login actions */
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGIN_ERROR = 'SESSION_LOGIN_ERROR';
export const SESSION_LOGIN_REQUEST = 'SESSION_LOGIN_REQUEST';
export const SESSION_LOGIN_RESPONSE = 'SESSION_LOGIN_RESPONSE';

/* User service actions */
export const USERS_FETCH_LIST = 'USERS_FETCH_LIST';
export const USERS_FETCH_LIST_ERROR = 'USERS_FETCH_LIST_ERROR';
export const USERS_FETCH_LIST_REQUEST = 'USERS_FETCH_LIST_REQUEST';
export const USERS_FETCH_LIST_RESPONSE = 'USERS_FETCH_LIST_RESPONSE';
export const USERS_CREATE = 'USERS_CREATE';
export const USERS_CREATE_ERROR = 'USERS_CREATE_ERROR';
export const USERS_CREATE_REQUEST = 'USERS_CREATE_REQUEST';
export const USERS_CREATE_RESPONSE = 'USERS_CREATE_RESPONSE';

/* OAuth 2.0 service actions */
export const CLIENTS_FETCH_LIST = 'CLIENTS_FETCH_LIST';
export const CLIENTS_FETCH_LIST_ERROR = 'CLIENTS_FETCH_LIST_ERROR';
export const CLIENTS_FETCH_LIST_REQUEST = 'CLIENTS_FETCH_LIST_REQUEST';
export const CLIENTS_FETCH_LIST_RESPONSE = 'CLIENTS_FETCH_LIST_RESPONSE';
