/* Session observer actions */
export const SESSION_CHANGED = 'SESSION_CHANGED';

/* Session login actions */
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGIN_ERROR = 'SESSION_LOGIN_ERROR';
export const SESSION_LOGIN_REQUEST = 'SESSION_LOGIN_REQUEST';
export const SESSION_LOGIN_RESPONSE = 'SESSION_LOGIN_RESPONSE';

/* User service actions */
export const USERS_FETCH_LIST = 'USERS_FETCH_LIST';
export const USERS_FETCH_LIST_ERROR = 'USERS_FETCH_LIST_ERROR';
export const USERS_FETCH_LIST_REQUEST = 'USERS_FETCH_LIST_REQUEST';
export const USERS_FETCH_LIST_RESPONSE = 'USERS_FETCH_LIST_RESPONSE';
